logo = """

                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                  
        GGGGGGGGGGGGG                                                                          iiii                                                    GGGGGGGGGGGGG                                                              
     GGG::::::::::::G                                                                         i::::i                                                GGG::::::::::::G                                                              
   GG:::::::::::::::G                                                                          iiii                                               GG:::::::::::::::G                                                              
  G:::::GGGGGGGG::::G                                                                                                                            G:::::GGGGGGGG::::G                                                              
 G:::::G       GGGGGGuuuuuu    uuuuuu      eeeeeeeeeeee        ssssssssss       ssssssssss   iiiiiiinnnn  nnnnnnnn       ggggggggg   ggggg      G:::::G       GGGGGG  aaaaaaaaaaaaa      mmmmmmm    mmmmmmm       eeeeeeeeeeee    
G:::::G              u::::u    u::::u    ee::::::::::::ee    ss::::::::::s    ss::::::::::s  i:::::in:::nn::::::::nn    g:::::::::ggg::::g     G:::::G                a::::::::::::a   mm:::::::m  m:::::::mm   ee::::::::::::ee  
G:::::G              u::::u    u::::u   e::::::eeeee:::::eess:::::::::::::s ss:::::::::::::s  i::::in::::::::::::::nn  g:::::::::::::::::g     G:::::G                aaaaaaaaa:::::a m::::::::::mm::::::::::m e::::::eeeee:::::ee
G:::::G    GGGGGGGGGGu::::u    u::::u  e::::::e     e:::::es::::::ssss:::::ss::::::ssss:::::s i::::inn:::::::::::::::ng::::::ggggg::::::gg     G:::::G    GGGGGGGGGG           a::::a m::::::::::::::::::::::me::::::e     e:::::e
G:::::G    G::::::::Gu::::u    u::::u  e:::::::eeeee::::::e s:::::s  ssssss  s:::::s  ssssss  i::::i  n:::::nnnn:::::ng:::::g     g:::::g      G:::::G    G::::::::G    aaaaaaa:::::a m:::::mmm::::::mmm:::::me:::::::eeeee::::::e
G:::::G    GGGGG::::Gu::::u    u::::u  e:::::::::::::::::e    s::::::s         s::::::s       i::::i  n::::n    n::::ng:::::g     g:::::g      G:::::G    GGGGG::::G  aa::::::::::::a m::::m   m::::m   m::::me:::::::::::::::::e 
G:::::G        G::::Gu::::u    u::::u  e::::::eeeeeeeeeee        s::::::s         s::::::s    i::::i  n::::n    n::::ng:::::g     g:::::g      G:::::G        G::::G a::::aaaa::::::a m::::m   m::::m   m::::me::::::eeeeeeeeeee  
 G:::::G       G::::Gu:::::uuuu:::::u  e:::::::e           ssssss   s:::::s ssssss   s:::::s  i::::i  n::::n    n::::ng::::::g    g:::::g       G:::::G       G::::Ga::::a    a:::::a m::::m   m::::m   m::::me:::::::e           
  G:::::GGGGGGGG::::Gu:::::::::::::::uue::::::::e          s:::::ssss::::::ss:::::ssss::::::si::::::i n::::n    n::::ng:::::::ggggg:::::g        G:::::GGGGGGGG::::Ga::::a    a:::::a m::::m   m::::m   m::::me::::::::e          
   GG:::::::::::::::G u:::::::::::::::u e::::::::eeeeeeee  s::::::::::::::s s::::::::::::::s i::::::i n::::n    n::::n g::::::::::::::::g         GG:::::::::::::::Ga:::::aaaa::::::a m::::m   m::::m   m::::m e::::::::eeeeeeee  
     GGG::::::GGG:::G  uu::::::::uu:::u  ee:::::::::::::e   s:::::::::::ss   s:::::::::::ss  i::::::i n::::n    n::::n  gg::::::::::::::g           GGG::::::GGG:::G a::::::::::aa:::am::::m   m::::m   m::::m  ee:::::::::::::e  
        GGGGGG   GGGG    uuuuuuuu  uuuu    eeeeeeeeeeeeee    sssssssssss      sssssssssss    iiiiiiii nnnnnn    nnnnnn    gggggggg::::::g              GGGGGG   GGGG  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee  
                                                                                                                                  g:::::g                                                                                         
                                                                                                                      gggggg      g:::::g                                                                                         
                                                                                                                      g:::::gg   gg:::::g                                                                                         
                                                                                                                       g::::::ggg:::::::g                                                                                         
                                                                                                                        gg:::::::::::::g                                                                                          
                                                                                                                          ggg::::::ggg                                                                                            
                                                                                                                             gggggg                                                                                               
                                                                          
"""